version: '3.2'

services:
  db:
    image: postgres:latest
    hostname: db
    container_name: db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: ''
      POSTGRES_DB: ''
    volumes:
    - data:/var/lib/postgresql/data
    restart: always

volumes:
  data:
    external: true