version: '3.7'

services:
  db:
    image: postgres:latest
    hostname: db
    container_name: db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: 
      POSTGRES_DB: schooldriving
    volumes:
    - data:/data
    - mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    restart: always

volumes:
  data:
    external: true